---
- name: Playbook for Docker installation
  hosts: app
  become: true # Выполнение от имени root
  tasks:
    - name: Ensure apt package list is updated (apt-get update)
      apt: # модуль ansible.builtin.apt
        update_cache: true
        cache_valid_time: 3600

    - name: Ensure Docker is set up
      include_role:
        name: docker

    - name: Run image
      community.docker.docker_container:
        name: app
        image: timurbabs/django
        state: started
        ports:
          - "8000:8000"
