---
- name: Playbook for Docker installation
  hosts: app
  become: true # Выполнение от имени root
  tasks:
    - name: Ensure apt package list is updated (apt-get update)
      apt: # модуль ansible.builtin.apt
        update_cache: true

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - apt-transport-https # https в apt для скачивания docker
          - ca-certificates # корневые сертификаты
          - curl
          - gnupg # docker проверяет подлинность пакетов через gpg ключи
          - software-properties-common

    - name: Create directory for Docker's GPG key
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Add Docker's official GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc

    - name: Ensure docker.asc has read permissions for all users
      file:
        path: /etc/apt/keyrings/docker.asc
        mode: "0644"
        state: file

    - name: Add Docker APT repository
      ansible.builtin.apt_repository:
        repo: >-
          deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc]
          https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        filename: docker
        state: present
        update_cache: yes

    - name: Install Docker and related packages
      apt:
        update_cache: true
        state: present
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin

    # Linux Docker postinstall
    - name: Add Docker group
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add user to Docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Enable and start Docker services
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - docker.service
        - containerd.service
    # - name: Install git
    #   apt:
    #     name: git
    #     state: present
    #
    # - name: Clone the repo
    #   git:
    #     repo: "https://github.com/mdn/django-locallibrary-tutorial.git"
    #     dest: /opt/app
    #     update: yes

    - name: Run image
      community.docker.docker_container:
        name: app
        image: timurbabs/django
        state: started
        ports:
          - "8000:8000"
        # volumes:
        #   - /opt/app:/app
